def get_keyword_map():
    return {
        'Division': 'Class',
        'InferredFrom': 'Inheritance',
        'WhetherDo': 'Condition',
        'Else': 'Condition',
        'Ire': 'Integer',
        'Sire': 'SInteger',
        'Clo': 'Character',
        'SetOfClo': 'String',
        'FBU': 'Float',
        'SFBU': 'SFloat',
        'None': 'Void',
        'Logical': 'Boolean',
        'TerminateThis': 'Break',
        'RotateWhen': 'Loop',
        'ContinueWhen': 'Loop',
        'ReplyWith': 'Return',
        'Seop': 'Struct',
        'Check': 'Switch',
        'situationof': 'Switch',
        'Program': 'Start Statement',
        'End': 'End Statement',
        'and': 'Logic operators',
        'or': 'Logic operators',
        'Using': 'Inclusion'
    }
